// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace RefrigeratedLayout
{
    public class RefrigeratedLayoutOutputs: ResultsBase
    {
		/// <summary>
		/// The number of doors
		/// </summary>
		[JsonProperty("Linear Feet")]
		public double LinearFeet {get;}


        
        /// <summary>
        /// Construct a RefrigeratedLayoutOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public RefrigeratedLayoutOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a RefrigeratedLayoutOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public RefrigeratedLayoutOutputs(double linearfeet): base()
        {
			this.LinearFeet = linearfeet;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}