// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace RefrigeratedLayout
{
    public class RefrigeratedLayoutInputs: S3Args
    {
		/// <summary>
		/// The minimum width of an aisle
		/// </summary>
		[JsonProperty("Min Aisle Width")]
		public double MinAisleWidth {get;}

		/// <summary>
		/// The width of each fixture
		/// </summary>
		[JsonProperty("Door Size")]
		public double DoorSize {get;}


        
        /// <summary>
        /// Construct a RefrigeratedLayoutInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public RefrigeratedLayoutInputs() : base()
        {
			this.MinAisleWidth = 4;
			this.DoorSize = 0.76;

        }


        /// <summary>
        /// Construct a RefrigeratedLayoutInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public RefrigeratedLayoutInputs(double minaislewidth, double doorsize, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.MinAisleWidth = minaislewidth;
			this.DoorSize = doorsize;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}