// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ProduceLayout
{
    public class ProduceLayoutInputs: S3Args
    {
		/// <summary>
		/// The minimum width of an aisle (in)
		/// </summary>
		[JsonProperty("Min Aisle Width")]
		public double MinAisleWidth {get;}


        
        /// <summary>
        /// Construct a ProduceLayoutInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ProduceLayoutInputs() : base()
        {
			this.MinAisleWidth = 144;

        }


        /// <summary>
        /// Construct a ProduceLayoutInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ProduceLayoutInputs(double minaislewidth, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.MinAisleWidth = minaislewidth;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}