// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace Checkout
{
    public class CheckoutInputs: S3Args
    {
		/// <summary>
		/// The width.
		/// </summary>
		[JsonProperty("Aisle Width")]
		public double AisleWidth {get;}


        
        /// <summary>
        /// Construct a CheckoutInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public CheckoutInputs() : base()
        {
			this.AisleWidth = 2;

        }


        /// <summary>
        /// Construct a CheckoutInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public CheckoutInputs(double aislewidth, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.AisleWidth = aislewidth;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}