// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace PreparedFoodLayout
{
    public class PreparedFoodLayoutInputs: S3Args
    {
		/// <summary>
		/// Counter Height (in).
		/// </summary>
		[JsonProperty("Counter Height")]
		public double CounterHeight {get;}

		/// <summary>
		/// The depth (in).
		/// </summary>
		[JsonProperty("Counter Depth")]
		public double CounterDepth {get;}


        
        /// <summary>
        /// Construct a PreparedFoodLayoutInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public PreparedFoodLayoutInputs() : base()
        {
			this.CounterHeight = 35;
			this.CounterDepth = 48;

        }


        /// <summary>
        /// Construct a PreparedFoodLayoutInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public PreparedFoodLayoutInputs(double counterheight, double counterdepth, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.CounterHeight = counterheight;
			this.CounterDepth = counterdepth;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}