// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ShelvingLayout
{
    public class ShelvingLayoutInputs: S3Args
    {
		/// <summary>
		/// The length.
		/// </summary>
		[JsonProperty("Length")]
		public double Length {get;}

		/// <summary>
		/// The width.
		/// </summary>
		[JsonProperty("Width")]
		public double Width {get;}

		/// <summary>
		/// The height.
		/// </summary>
		[JsonProperty("Height")]
		public double Height {get;}

		/// <summary>
		/// The depth of one side of a shelving unit
		/// </summary>
		[JsonProperty("Shelving Depth")]
		public double ShelvingDepth {get;}

		/// <summary>
		/// The minimum width of an aisle
		/// </summary>
		[JsonProperty("Min Aisle Width")]
		public double MinAisleWidth {get;}


        
        /// <summary>
        /// Construct a ShelvingLayoutInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ShelvingLayoutInputs() : base()
        {
			this.Length = 100;
			this.Width = 100;
			this.Height = 10;
			this.ShelvingDepth = 1.5;
			this.MinAisleWidth = 4;

        }


        /// <summary>
        /// Construct a ShelvingLayoutInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ShelvingLayoutInputs(double length, double width, double height, double shelvingdepth, double minaislewidth, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.Length = length;
			this.Width = width;
			this.Height = height;
			this.ShelvingDepth = shelvingdepth;
			this.MinAisleWidth = minaislewidth;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}